Remove empty line in microchip_pic32mcu.dcm
It was added in:
c950402ffed68754612a4c4dbc91fd8aa9ea68d7

It made eeschema error with:
from sch_legacy_plugin.cpp : loadDocs() line:2271
20:19:41: Part library '/usr/share/kicad/library/microchip_pic32mcu.lib'
failed to load. Error:
 IO_ERROR: expected token in symbol definition in input/source
 '/usr/share/kicad/library/microchip_pic32mcu.dcm'
 line 5

When KiCad was built with KICAD_USE_SCH_IO_MANAGER=ON